### ISSUE TITLE
Change email templates according to this content

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#113]
Where we have put together a copy already, I have specified below: 

* Email to admin when a new CV has been submitted
* Email to client when approved to use Harness

>You've been approved to use Harness!
Click here to come and get started!

* Email to client if they've been rejected by the admin:

>Sorry...
We decided you weren't quite right to use the platform

*  Email to agency when client has accepted a candidate for a job:

>Congratulations!
Your candidate, -candidateName-, has been accepted by the client for the -jobTitle- vacancy
You'll be able to track their progress in your 'My Jobs' page

* Email to agency when there's a new vacancy:

>Hi there!
There's a new vacancy for you to check out on Harness!
Please go the URL you were emailed to view the new vacancy

* Email to admin when an agency has submitted a CV:

>-agencyName-  submitted a new candidate!
It's on the -jobTitle- vacancy at -companyName- 
Click here to view the vacancy page

* Email to client when admin removes a vacancy:

>Sorry, your vacancy on Harness for a -jobTitle- has been deleted
Either the information was inaccurate or the vacancy was idle, but we'd love you to come back and submit another vacancy sometime!

* Email to agency if admin rejects their CV:

>Sorry...
We felt -candidateName- wasn't the right fit for the -jobTitle- vacancy at  -companyName- 

* Email to client when Admin notifies them of new candidates:

>You've got new candidates to look at!
On your -jobTitle- vacancy we've supplied you with a rated shortlist of potential candidates
Come have a look!

* Email to agency when the admin accepts their candidate:

>Good news!
-candidateName-  has been approved for the -jobTitle- + vacancy at -companyName-!
The client will now be reviewing the candidate and we'll let you know if they get accepted!

*  Email to agency with feedback when the client rejects their candidate:

 >Sorry to tell you...
-candidateName- wasn't was quite right for the -jobTitle- vacancy at -companyName-...
The client said your candidate didn't have enough experience / their experience wasn't quite right for the role

...and what do we want to put on the end of the email? Perhaps something like 'please come and talk to us at [email] if you have any questions

**Comment by Benbrierley** [comment]
Where we have put together a copy already, I have specified below:
•	Email to admin when a new CV has been submitted
•	Hi!  A new CV has been submitted for the role of *******.
•	Email to client when approved to use Harness
•	Hi FIRST NAME, You've been approved to use Harness!
Click here to come and get started,
•	Email to client if they've been rejected by the admin:
•	Oops, sorry, it doesn’t look like you’ve been accepted onto Harness, get in touch with us here to find out how you can!
•	Email to agency when client has accepted a candidate for a job:
•	Hey FIRST NAME Great news! Your candidate, FULL NAME, has been accepted by CLIENT NAME for the role of  JOB TITLE. You’ll be able to track their progress in your “My Jobs” page
•	Email to agency when there's a new vacancy:
Hi there!
There's a new vacancy for you to check out on Harness!
Please go the URL you were emailed to view the new vacancy
•	Email to admin when an agency has submitted a CV:
-agencyName- submitted a new candidate!
It's on the -jobTitle- vacancy at -companyName- 
Click here to view the vacancy page
•	Email to client when admin removes a vacancy:
Sorry, your vacancy on Harness for a -jobTitle- has been deleted
either the information was inaccurate or the vacancy was idle, but we'd love you to come back and submit another vacancy sometime! Get in touch here to find out more.
•	Email to agency if admin rejects their CV:
Sorry...
We felt -candidateName- wasn't the right fit for the -jobTitle- vacancy at -companyName- give us a call if you would like us to explain why!
•	Email to client when Admin notifies them of new candidates:
You've got new candidates to look at!
On your -jobTitle- vacancy we've supplied you with a rated shortlist of potential candidates
Come have a look!
•	Email to agency when the admin accepts their candidate:
Good news!
-candidateName- has been approved for the -jobTitle- + vacancy at -companyName-!
The client will now be reviewing the candidate and we'll let you know if they get accepted!
•	Email to agency with feedback when the client rejects their candidate:
Sorry to tell you...
-candidateName- wasn't was quite right for the -jobTitle- vacancy at -companyName-...
The client said your candidate didn't have enough experience / their experience wasn't quite right for the role
...and what do we want to put on the end of the email? Perhaps something like 'please come and talk to us at [email] if you have any questions
Yes, I think your Copy is great for the time being, and giving them an email address or number would be best!

**Comment by hdrdavies** [comment]
Thanks @Benbrierley really helpful!

**Comment by hdrdavies** [comment]
New copies as per Ben's comment above progress:

- [x] Email to client when approved to use Harness 
- [x] Email to client if they've been rejected by the admin
- [ ] Email to agency when client has accepted a candidate for a job
- [ ] Email to client when admin removes a vacancy
- [ ] Email to agency if admin rejects their CV
