### ISSUE TITLE
Hompage template

### ISSUE THREAD

**Issue by tormod17** [hutosaha/hrns-#135]
-image to follow.

**Comment by tormod17** [comment]
https://invis.io/ZB76LCO8X#/155859909_Harness-Faces-3

**Comment by mk4111** [comment]
@carlstratton the link above seems to be expired.
Please could you provide some feedback on the existing page? Thank you!

**Comment by carlstratton** [comment]
@mk4111 @tormod17 You can use this for now: https://invis.io/ZB76LCO8X#/155859909_Harness-Faces-3

**Comment by mk4111** [comment]
@carlstratton thank you!

**Comment by mk4111** [comment]
- [ ] testimonials layout
