### ISSUE TITLE
Candidate sign up page

### ISSUE THREAD

**Issue by joshbrierley** [hutosaha/hrns-#150]
2 issues I have just had in trying to sign up as candidate:

# Cannot 'submit' my sign up after attaching file. Button faded out as if out of use
# 'Home' button doesn't work

**Comment by mk4111** [comment]
@joshbrierley could you please let us know which page you would like to be redirected to?
Candidate doesn't have a dashboard, so the only options are to redirect you to the pre-login page, or to the 'submit an updated profile' page (which is what it is currently on).

The button only becomes blue once the file has been uploaded properly - we've just checked this, and think that this is functional. Please let us know if you have an issue with the uploading!

Thank you!

**Comment by joshbrierley** [comment]
@mk4111 All good, the upload file is working fine now I just tried it. It wasn't working yesterday when I tried but perhaps because you were working on it? The HOME page button seems fine  too as yesterday it didn't redirect at all.

Cheers!

**Comment by mk4111** [comment]
@joshbrierley great! thank you!
