### ISSUE TITLE
Ben's Feedback

### ISSUE THREAD

**Issue by Benbrierley** [hutosaha/hrns-#151]
1. The Salary Scroller function found next the Salary box in "Submit a Job" goes up in 1's, and even -1's. Can we change this to scrolling in £1000's or just get rid of it?
2.Ideally, personality fit and Culture boxes would be next to each other.
3. Change the Timescale for Search title, to Ideal Start Date
4.The date is in American Format - can we change this please.
5. The Client's "Submit a job" form times out this morning when we took over 10 minutes to fill it out, and it broke the system - maybe you were just working on it at the time?

**Comment by mk4111** [comment]
(1) 
HTML 5 research:
- [ ] Can we set increment size?
- [ ] Can we set minimum val? 
else
- [ ] Remove number type?

**Comment by tormod17** [comment]
@mk4111  can we close this ?
