### ISSUE TITLE
Agency informed of a new vacancy

### ISSUE THREAD

**Issue by Benbrierley** [hutosaha/hrns-#157]
All I received was the below; what URL is it referring too, and why cant we include the same button we do when we email clients saying they have an interview to arrange? Something needs to be in this email that I can click on. @tormod17  @carlstratton 

Hi there!

There's a new vacancy for you to check out on Harness!

Please go the URL you were emailed to view the new vacancy

ben.brierley@sailixsearch.com

07469249766

**Comment by tormod17** [comment]
@Benbrierley  no problem we can use the same button.
