### ISSUE TITLE
Agency Email Address should not be visible to client

### ISSUE THREAD

**Issue by Benbrierley** [hutosaha/hrns-#159]
On the Scheduling page - otherwise the client will use this to contact agency direct, which we want to avoid at all costs.

This could be replaced with desired salary. @tormod17 @mk4111

**Comment by tormod17** [comment]
@Benbrierley  understood I will change the scheduling page.  
@Benbrierley @carlstratton @carlstratton   what about the confirmation of appointment page do you want the agency details to be supplied at that point ?  should the client need to get hold of the agent last minute ?

**Comment by Benbrierley** [comment]
@tormod17 we dont want the agency contact details shown anywhere on any client screen really - you make a good point, but in the case of emergencies, Harness Account Managers will be the point of contact.

**Comment by tormod17** [comment]
@Benbrierley  understood I've removed them
