### ISSUE TITLE
Design Page

### ISSUE THREAD

**Issue by Benbrierley** [hutosaha/hrns-#166]
Hi @tormod17 

I am sure you are onto this, but a few things.

1. The picture cuts off faces in the background image, and doesnt align at the bottom.
2. The writing needs to be smaller, and lower and narrower, so it doesn't block the images.
3. @carlstratton the blue icons are too blue, it looks overpowering and washed out (I know your screen is different) can we do them in black? It will look slicker.
4. The HARNESS logo needs to be black and not blue at the top of the page.
5. @carlstratton I know you hate me now, but the white bar at the top, spoils the impact of the image, can we put the HARNESS logo bigger, and in white on top of the HERO image in the middle?
6. If I was being really fussy, which I am as you know now, I'd say the How It Works logos are too big, and we need to lose the "Trusted By" for the time being, until I have that sorted!
7. The writing explaining everything beneath the top fold needs to be bigger, it is far too small at the moment.

**Comment by carlstratton** [comment]
Hey All,

I don't have time to comment on anything apart from the below.

• Only use the black logo in the navigation throughout the site – on the
colour, as we know ALL screens are different, some more clarity and
brightness than the Apple, others worst and lower density than the HP. We
can't design for one; however, *if* we were to design for one it would be
Apple, simply because it's the industry standard for design in general.
Simples!

• The images cut off the top and bottom, it's either that or on the sides –
maybe sides makes more sense.

Will feedback more tomorrow morning, when I get a look at the site.

Cheers





Carl


*— *

t: 07824 632 199
e: cgstratton@gmail.com

senior UX designer at farfetch <http://www.farfetch.com>
co-founder | emblzn.com
designer | carlstratton.co.uk

**Comment by tormod17** [comment]
Trying to fix a bug with appointment maker will have a go on the frontend wants completed- I have sorted the viewer for 'Word and 'pdf '- Alos will need to sign up for various services as well.  @carlstratton  @Benbrierley

**Comment by tormod17** [comment]
- [ ]  The picture cuts off faces in the background image, and doesnt align at the bottom.
- [ ] The writing needs to be smaller, and lower and narrower, so it doesn't block the images.
@carlstratton the blue icons are too blue, it looks overpowering and washed out (I know your screen is different) can we do them in black? It will look slicker.
- [ ] The HARNESS logo needs to be black and not blue at the top of the page.
@carlstratton I know you hate me now, but the white bar at the top, spoils the impact of the image, can we put the HARNESS logo bigger, and in white on top of the HERO image in the middle?
- [ ]If I was being really fussy, which I am as you know now, I'd say the How It Works logos are too big, and we need to lose the "Trusted By" for the time being, until I have that sorted!
- [ ] The writing explaining everything beneath the top fold needs to be bigger, it is far too small at the moment.

**Comment by tormod17** [comment]
@Benbrierley  @carlstratton let me know what to do with logo I have made the other changes as @Benbrierley requested.

**Comment by carlstratton** [comment]
@tormod17 looking good, see some style changes from me.

1. Increase size of sign in buttons

.ui.linkedin.button {
    marign: 5em;
    border-radius: 0px;
    background-color: #19b7ca;
    width: 170px;
    height: 50px;
}

2. Increase distance of Find your human PARAGRAPH and 'Sign in as' copy by adding:
margin-top: 40px

3. Find out more down arrow should sit at the bottom of the top black section (see invision/Zeplin visual)

4. 'how it works' and 'why harness' titles are the wrong weight, they should be thinner in width

5. Click smile hire copy is too small, paragraph copy below is too big, can you use styling in Zeplin for both of these please.

6. Icon size and styling of Why Harness section should be inline with the Zepin visual, the width should also be reduced, again see Zeplin please.

7. All paragraph copy below the hero section should use Open Sans - Regular at size 1em (currently font size 130%)

8. Agency login link is incorrect

@tormod17 Thanks so much for this.

@Benbrierley See what the page looks like after this, it should come together.

**Comment by tormod17** [comment]
@carlstratton  zeplins great but the sizes aren't fully accurate font size can't be e.g. 8px. 
I 've had a go at your points and adjusted to suit. 
@Benbrierley  @carlstratton agency login , what has happened to the obscure login we're sending agents are you now wanting agents to access the site directly from the home page. ?

**Comment by carlstratton** [comment]
Morning @tormod17 , hope you had a good weekend. 

Re: the px to em conversion, check out this site for sizing conversions: http://pxtoem.com/

The agency link at the bottom was a last resort, just incase someone lost their obscure login – I thought it would be as easy as adding a link, let me know if it's any more trouble than that.

Thanks

@Benbrierley

**Comment by tormod17** [comment]
@carlstratton  no problems I will add the obscure endpoint to the anchor link. Sizes, I'm aware of the size conversions but the Zeplin page doesn't represent a full screen e.g. 8px is 0.5em which is tiny.  I have though used it as a guide and updated the home page. waiting to get linked in account and heroku sorted with credit card then I'll get you running on your domain name. @Benbrierley

**Comment by carlstratton** [comment]
Hey @tormod17 that's a tricky one, you're right 8px is tiny! Not quite sure what to do as some of the details really are becoming DETAILS on the page now, I think it's going to be a case of us sitting down for an hour and getting through them. There are only like 5 main points I can see, all of which focus around the weight of the text on the page, and the distribution of heavy, bold and regular font weights. Also, the hero image has gone and squashed itself now! lol. I'm aware these changes seem never ending! I promise the end is close! @Benbrierley I'm not free until next week now as I'm on holiday from Wednesday to go through these minor changes with @tormod17 – maybe you guys want to close all other issues in the mean time?

**Comment by tormod17** [comment]
@Benbrierley @carlstratton  Can I double check you want agency login on home page as that will mean any agent can just go straight through once signed up with linkedin.  You take away the exclusivity of which agents can visit the site.  Point to note also is that once an agent has logged in through linkedin the next time they visit the site they will be taken directly through to their dashboard.

**Comment by carlstratton** [comment]
@tormod17 I thought they had to be approved by Harness before going through to the platform?

**Comment by tormod17** [comment]
@carlstratton  agents don't get approved only clients. The idea was that only certain agents would be given the unique endpoint allowing them access to the site.  There is no other way for an agent  to access the site.  Once they  authenticate with Linkedin the next time they visit harness they will have access as their details will be stored in a cookie.

**Comment by Benbrierley** [comment]
@carlstratton we dont want any sucker getting into Harness as an agent, but what would be good is perhaps  an email address for them to get in touch with us if they are interested in the footer?

**Comment by carlstratton** [comment]
@Benbrierley totally agree, I was going to suggest the same thing!
@tormod17 @joshbrierley

**Comment by Benbrierley** [comment]
agency@harnesstalent.com

**Comment by Benbrierley** [comment]
@tormod17 @carlstratton  I assume you guys are fixing the squashed background image and the black line at the bottom of the image?

**Comment by Benbrierley** [comment]
Also, full stop missing (the last word of the Why us? After the words "no seriously, it's true"

Also, the white line between "why us" and About us" sections.

**Comment by Benbrierley** [comment]
@tormod17 just noted my typo - sorry

QUICKER

Harness requires you to do nothing but review high quality, relevant and available CV's in **ONE** simple place. Zero admin. We cut through the nonsense of recruiting, and free you up to do important stuff!
