### ISSUE TITLE
Admin: ability to accept / reject CVs for a specific vacancy & give ratings for each CV

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#21]

**Comment by tormod17** [comment]
Great work mate you seem to have completed most of this issue, what is the 'notify client' button for ?  once rated this goes straight into the client short list automatically and is viewable on their dashboard . Should we not also send them an automatic email  at the same time as sending the agency one.

**Comment by hdrdavies** [comment]
So 'notify client' will be an easy way for the admin to control when messages get sent to the client. Otherwise if it's done every time a new candidate has been approved it could prove pretty spammy!

**Comment by hdrdavies** [comment]
Resolved :+1:
