### ISSUE TITLE
Client user-flow diagram

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#24]

**Comment by tormod17** [comment]
[Client user-flow diagram](https://drive.google.com/drive/search?q=type:image)

**Comment by tormod17** [comment]
![sailing-client-plan](https://cloud.githubusercontent.com/assets/11330267/13754212/0a33f376-ea0e-11e5-84a1-67d5ca0418d7.jpg)

**Comment by hdrdavies** [comment]
From meeting:
-Don't need to show agency details next to candidate
-Need to track scheduling info for the client to track #29

**Comment by tormod17** [comment]
Vacancy Page: 
-  Upload button  not necessary

**Comment by hdrdavies** [comment]
We're going to combine vacancy page  & scheduling #17 #18 #19 #20 - to look like the wireframes here:

http://ovw7jm.axshare.com/#p=client__candidate_progress_overview&g=1

**Comment by hdrdavies** [comment]
Closing this - holds reference info
