### ISSUE TITLE
Agency user-flow diagram 

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#25]
![img_20160315_105654504](https://cloud.githubusercontent.com/assets/13098199/13775571/2eb92ee8-ea9d-11e5-8179-4b5fae546d84.jpg)

**Comment by tormod17** [comment]
FROM MEETING - 
Two vacancy overview lists . First view is all vacancies .  Second view, vacancies that  the agency has submitted CV's against , also displays the stage at which they are at in the application process.

**Comment by hdrdavies** [comment]
Agency has a obscure end-point to log in, so 'log-in for agency' is not displayed on the root landing page

**Comment by tormod17** [comment]
#12 and #13 should share the same submit vacancy page as per [Carl's wire frame ](http://ovw7jm.axshare.com/#p=agency__submit_candidate&g=1)

**Comment by hdrdavies** [comment]
Closing this - holds reference info
