### ISSUE TITLE
Admin user-flow diagram

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#26]
* Don't need to automate the notification to agencies on accepting / rejecting (this might change - see minutes #38)
* Notify the client by email when the admin approves a bunch of candidates

![rsz_img_20160315_120621380](https://cloud.githubusercontent.com/assets/13098199/13777246/d1c6551c-eaa6-11e5-9a09-a2e4d5d7ddb1.jpg)

**Comment by hdrdavies** [comment]
Don't need to automate the notification to agencies

**Comment by hdrdavies** [comment]
Notify the client when the admin approves a bunch of candidates

**Comment by hdrdavies** [comment]
Don't need to notify the agencies of rejected candidates or accepted candidates

**Comment by tormod17** [comment]
Overview information (scheduling) will be the same as view as Client, therefore same database query.

**Comment by hdrdavies** [comment]
Closing this - holds reference info
