### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by tormod17** [hutosaha/hrns-#28]
#### Auth & Authorisation in hapi 
https://medium.com/@poeticninja/authentication-and-authorization-with-hapi-5529b5ecc8ec#.tk3o3pp04

#### Form uploading in hapi   
https://bl.ocks.org/joyrexus/0c6bd5135d7edeba7b87

#### Mailgun
https://github.com/1lobby/mailgun-js 

#### Semantics UI 
http://semantic-ui.com/
https://www.youtube.com/watch?v=pSKGEob1sQo

**Comment by tormod17** [comment]
https://medium.com/@poeticninja/authentication-and-authorization-with-hapi-5529b5ecc8ec#.tk3o3pp04

Form uploading in HAPI:-    https://bl.ocks.org/joyrexus/0c6bd5135d7edeba7b87

https://github.com/1lobby/mailgun-js

**Comment by tormod17** [comment]
Carl has suggested Semantics UI, 
http://semantic-ui.com/
 https://www.youtube.com/watch?v=pSKGEob1sQo

**Comment by tormod17** [comment]
[Linkedin Oauth example ](https://github.com/tormod17/linkedin-oauth-example);

**Comment by hdrdavies** [comment]
### Hapi user scopes

https://blog.andyet.com/2015/06/16/harnessing-hapi-scopes/
http://stackoverflow.com/questions/29052940/role-based-authentication-in-hapijs

**Comment by hdrdavies** [comment]
Doesn't need to be open - reference information :+1:
