### ISSUE TITLE
Additional features (holds Carl's original wireframes)

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#29]
Agency and client can have 'overviews' of candidates, which tracks their progress

http://ovw7jm.axshare.com/#p=client__my_jobs&g=1

http://ovw7jm.axshare.com/#p=agency__jobs_overview_1&g=1

**Comment by tormod17** [comment]
http://ovw7jm.axshare.com/#p=agency__jobs_overview_1&g=1

Agency job overview - what does the edit button lead to ?

**Comment by tormod17** [comment]
http://ovw7jm.axshare.com/#p=generic_homepage&g=1

This page will no longer apply as we've agreed the home page will be 'I'm a client' and 'I'm a candidate'  buttons.

**Comment by hdrdavies** [comment]
Already raised the additional features as other issues.
