### ISSUE TITLE
Missing Wire-frames.  

### ISSUE THREAD

**Issue by tormod17** [hutosaha/hrns-#32]
http://ovw7jm.axshare.com/#p=job_overview&g=1

**Comment by hdrdavies** [comment]
@carlstratton 

Hi Carl! We've been through our own wireframes and the wireframes we walked through on Wednesday and there are a few missing. If you don't mind providing these we would be very grateful:

-Client & Candidate - Home page to login
-Client - Sign-up page (form with details on), with pop up saying we'll be in touch
-Agency - Obscure log-in page for agencies
-Agency - Individual vacancy page (we have the wireframe for an agency but this doesn’t display the candidates the agency themselves have put forward for the role- we need to figure out the best way to display this)
-Admin - Login page
-Admin - Dashboard (options to go 'User info', 'Approval Page' and 'Vacancies')
-Admin - Approval page #11 (grabs users who haven't been approved yet)
-Admin- User info page #10 (list view of everyone on the site)
-Admin- (All) Vacancies page #21 (can delete vacancies here) - overview info available here - this will look like Client - My jobs
-Admin- Individual vacancy page - accept / decline CVs + categorise - email notification for client when CVs are accepted

Let us know if you need any further info but everything should be in the appropriate issue in this repo. 

Thanks Carl!

**Comment by tormod17** [comment]
### All Wire-frames in order of user flow

######  * lines are pages we are waiting for.  

#### Client

-Client & Candidate - Home page to login. *
-Client - Sign up page (form with details on), with pop up saying we'll be in touch.*
-Client - My vacancies page / My jobs (shows overview of progress of candidates)  ( tab for create Vacancy) 
-Client - Create vacancy page (with form) 
-Client- Individual vacancy page (holds list of C-Client & Candidate - Home page to login. *
-Client - Sign up page (form with details on), with pop up saying we'll be in touch.*
-Client - My vacancies page / My jobs (shows overview of progress of candidates)  ( tab for create Vacancy) 
-Client - Create vacancy page (with form) 
-Client- Individual vacancy page (holds list of CVs approved by admin, you can click through to scheduling)
-Client - Individual vacancy scheduling page

#### Agency

-Agency - Obscure log-in page for agencies /  linked in button to sign in. *
-Agency - Sign up page (form with details), with pop up saying we'll be in touch - Wireframe: ‘Agency - agency details’ (no image upload or password fields)
-Agency - Live vacancies page - all the vacancies posted by companies - Wireframe is Agency: My Jobs
-Agency - 'My jobs' (Carl's name) / 'My vacancies' page - All the vacancies for which the agency has put candidates forward for - overview of candidate progress - Wireframe ‘Agency - jobs overview’: edit will become view
-Agency - Individual vacancy page (we have the wireframe but this doesn’t display the candidates the agency themselves have put forward for the 
-Agency - generic upload page - they can submit a candidate not aligned to a vacancy - this goes straight to harness - Wireframe is agency - submit candidate (then display message saying the information will be available as an overview in My vacancies when the client accepts the candidate)


#### Candidate 

-Client & Candidate - Home page to login.*
-Candidate - Login page*
-Candidate - Submit CV page (same upload form as for agencies) - Wireframe: agency: submit candidate - but without specific job title

#### Admin

-Admin - Login page*
-Admin - Dashboard (options to go 'User info', 'Approval Page' and 'Vacancies' *
-Admin - Approval page #11 (grabs users who haven't been approved yet)*
-Admin- User info page #10 (list view of everyone on the site)*
-Admin- (All) Vacancies page #21 (can delete vacancies here) - overview info available here - this will look like Client - My jobs*
-Admin- Individual vacancy page - accept / decline CVs + categorise - email notification for client when CVs are accepted*Vs approved by admin, you can click through to scheduling)

**Comment by Benbrierley** [comment]
@hdrdavies The question regarding feedback after a candidate is rejected; I envisioned 4 options;
1. Not enough relevant experience.(Tick Box) Details Optional (Text box)
2. Not the right culture fit. (Tick box) Details Optional (Text Box)
3. Other (Text box)

**Comment by hdrdavies** [comment]
@Benbrierley Great, thanks! We'd love to hear from @carlstratton to know how this would look. No huge rush on that though as we're not planning to build that page for at least another week. 

In terms of the signup details - we can't quite remember... now that you're giving agencies the obscure endpoint on which to login - do they need to signup with details / do they need to be approved by the admin before they're allowed on the site?

**Comment by carlstratton** [comment]
Hey Guys, just looking at the wires and sorry to be a complete pain but this way of working doesn't feel totally efficient as i'm creating wires without a spec. Are you free for a couple of hours on Wednesday to catchup with the dev progress but to also hand sketch the wires we need to continue. Sorry to leave this so late, if we sketch them on Wednesday i'll get them all done over the weekend. Fingers crossed you have enough to continue until then?

**Comment by joshbrierley** [comment]
Hey guys,


Is everyone coming in for 6:30 this eve?


Josh


Josh Brierley
Consultant

T:  02037523043 M: 07770973292 E:Josh.Brierley@SailixSearch.com<mailto:ben.brierley@sailixsearch.com>
W: www.sailix.co.uk<http://www.sailix.co.uk/>  A: Sailix Ltd. 3rd Floor, 207 Regent St. London W1B 3HH.

TWITTER<https://twitter.com/SailixUK>   FACEBOOK<https://www.facebook.com/sailix> LINKEDIN<https://www.linkedin.com/company/9999596?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A1-1-1%2CtarId%3A1435564127004%2Ctas%3Asailix>

TECHNOLOGY TALENT. DIGITALLY REMASTERED.
[SAILIX VIBE]

Confidentiality Notice: The information contained in this email and any attachments is confidential. It is intended only for the named addressee(s). If  you are not the named addressee, please notify the sender immediately and do not disclose, copy or distribute the contents to any person other than the intended addressee(s). Company Registration Number: 9465157 Sailix Ltd, 2 Kelney, Melksham. Wilts. SN10 6ET.


________________________________

**Comment by carlstratton** [comment]
Yep. I'll be there.

Carl


*— *

t: 07824 632 199
e: cgstratton@gmail.com

head of UX and design | trueafrica.co
co-founder | emblzn.com
designer | carlstratton.co.uk

**Comment by tormod17** [comment]
Yes will see you 6:30.

**Comment by hdrdavies** [comment]
Doesn't need to be open - reference information
