### ISSUE TITLE
Format dates correctly with datepicker & fix datepicker

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#54]
An error comes up with moment when running the tests. We might want to adjust the format of the date which is returned by the datepicker to avoid the deprecation problem:

https://github.com/moment/moment/issues/1407

Solution here:

http://stackoverflow.com/questions/1328025/jquery-ui-datepicker-change-date-format

**Comment by hdrdavies** [comment]
Seems to be rendering strangely on firefox:- 

![image](https://cloud.githubusercontent.com/assets/13098199/14499655/1196b57c-0197-11e6-9c34-a40a8ff6650b.png)

**Comment by hdrdavies** [comment]
Didn't manage to fix this.... 

Perhaps try ignoring inherited styles? 

http://stackoverflow.com/questions/946645/how-to-ignore-parent-css-style

**Comment by tormod17** [comment]
added jquery-ui theme (css) cdn link to head.
