### ISSUE TITLE
Minutes of meeting 13/04/2016

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#59]
Questions: 

* What do you want displayed to candidates who have already submitted their CV once?
* What do you want displayed to agencies once they've submitted a generic CV?
* On the Admin vacancy page - would you like the email printed out for the agency? 

Agenda:

* Walkthrough github
* Walkthrough application

**Comment by Benbrierley** [comment]
1. Hey! Great to see you again, but don't worry, we have your CV already - if you would like too submit an updated profile, try here!
2. Great job! You have just potentially helped your candidate find their next job, introduced them with the best employer brands globallu, and increased your chance at making another fee. Easy, huh? Now sit back, relax, and we will be in touch to let you know if they have been accepted onto Harness.
3 . I don't understand!

**Comment by hdrdavies** [comment]
* document viewing library
* Carl's validation bug on email 
* Estimate extras scope

**Comment by carlstratton** [comment]
That looks good, I'll send over the sketch visuals on Monday for you guys to go by.

**Comment by hdrdavies** [comment]
@Benbrierley If we show them this message:

>Great job! You have just potentially helped your candidate find their next job, introduced them to the best employer brands globally, and increased your chance at making another fee. Easy, huh? Now sit back, relax, and we will be in touch to let you know if they have been accepted onto Harness.

every time they submit a CV, it might sound pretty crazy. Is there something you could put together which might sound alright if they see it over and over again?

**Comment by Benbrierley** [comment]
OK good point. How about

Good job! We will be in touch shortly to let you know if your candidate has been accepted.

**Comment by hdrdavies** [comment]
Yep that works nicely :+1:
