### ISSUE TITLE
Address joiSchema regex bug

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#68]
From Carl filling out job description:

https://hrns.herokuapp.com/submitjob

{"statusCode":400,"error":"Bad Request","message":"child \"jobDescription\" fails because [\"jobDescription\" with value \"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor turpis vel aliquam dapibus. Mauris dignissim lorem nunc, eu hendrerit dui vulputate non. Aliquam erat volutpat. Integer in pulvinar libero. Pellentesque euismod urna orci, aliquet venenatis neque bibendum eget. Proin pellentesque lobortis nulla non sodales. Vestibulum malesuada tortor bibendum quam hendrerit ultricies. Duis mattis faucibus leo, sit amet posuere sapien consectetur quis. Sed nulla nunc, aliquam id sem nec, suscipit gravida odio. Sed aliquam, sem eget blandit pretium, nisi orci iaculis massa, ut imperdiet diam arcu et nibh. Suspendisse potenti. Praesent commodo turpis lectus, a vulputate mi dictum quis. Morbi imperdiet consequat tellus, vitae suscipit sem. Proin condimentum vitae eros in semper.&#x0d;&#x0a;\" fails to match the required pattern: /^[-a-zA-Z0-9 .,£$€?@!+\\'()\\#\\&\\^\\%\\\"\\{\\}\\=\\~\\:\\;]*$/]","validation":{"source":"payload","keys":["jobDescription"]}}

**Comment by tormod17** [comment]
removed $ sign form back end regex now acepts lorem epsom
