### ISSUE TITLE
Harness UI design

### ISSUE THREAD

**Issue by carlstratton** [hutosaha/hrns-#76]
![safari-psd-mockup](https://cloud.githubusercontent.com/assets/1009195/14617937/2f1c5254-05a8-11e6-9088-04ba2b00e32a.png)
![untitled-1](https://cloud.githubusercontent.com/assets/1009195/14617949/351f4058-05a8-11e6-9ea0-47cf3a2b8bf6.png)

**Comment by hdrdavies** [comment]
Closing issue, referencing it elsewhere
