### ISSUE TITLE
Remove 'id' printing out on candidate page once we've received all linkedin IDs for admins

### ISSUE THREAD

**Issue by hdrdavies** [hutosaha/hrns-#79]
http://hrns.herokuapp.com/

Login as a candidate and it'll be at the top of the page.

**Comment by hdrdavies** [comment]
@joshbrierley @carlstratton still need your IDs!

**Comment by joshbrierley** [comment]
Could you re send the link? Sorry I cant find it


Josh Brierley
Consultant

T:  02037523043 M: 07770973292 E:Josh.Brierley@SailixSearch.com<mailto:ben.brierley@sailixsearch.com>
W: www.sailix.co.uk<http://www.sailix.co.uk/>  A: Sailix Ltd. 3rd Floor, 207 Regent St. London W1B 3HH.

TWITTER<https://twitter.com/SailixUK>   FACEBOOK<https://www.facebook.com/sailix> LINKEDIN<https://www.linkedin.com/company/9999596?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A1-1-1%2CtarId%3A1435564127004%2Ctas%3Asailix>

TECHNOLOGY TALENT. DIGITALLY REMASTERED.
[SAILIX VIBE]

Confidentiality Notice: The information contained in this email and any attachments is confidential. It is intended only for the named addressee(s). If  you are not the named addressee, please notify the sender immediately and do not disclose, copy or distribute the contents to any person other than the intended addressee(s). Company Registration Number: 9465157 Sailix Ltd, 2 Kelney, Melksham. Wilts. SN10 6ET.


________________________________

**Comment by hdrdavies** [comment]
@joshbrierley 

http://hrns.herokuapp.com/

and log-in as a candidate

**Comment by hdrdavies** [comment]
Referenced this in another issue...
