### ISSUE TITLE
Marketing page

### ISSUE THREAD

**Issue by carlstratton** [hutosaha/hrns-#90]
Hi Guys, here's the first look at the marketing page. It's pretty simple. The images might change but the layout will be similar – Let us know your thoughts in terms of complexity. 

https://projects.invisionapp.com/share/YP728SEDB#/screens/153032043_Desktop_HD

**Comment by hdrdavies** [comment]
Hiya @carlstratton,

So would you want this to be the home page / landing page? We haven't currently got sign-ups on that page, but users are taken to sign-ups if it's their first time logging in. It might be best to keep it that way in the interest of time. 

We can certainly put up some testimonials etc. but we'd need the content first. Similarly the image - do you want to go for that particular one - and if so - would you mind linking to where you found it?

@Benbrierley @joshbrierley

**Comment by carlstratton** [comment]
Hey Huw,

I think if we lead with that image for now, we can replace it later–We're
still trying to decide on the tone, visual language. Re the image itself, I
created it, and can share a file with you think evening, along with with
logo and any other images you might need.

Not a problem.

Shall we catchup on Wednesday for an overall review?

Thanks,


Carl


*— *

t: 07824 632 199
e: cgstratton@gmail.com

senior UX designer at farfetch <http://www.farfetch.com>
co-founder | emblzn.com
designer | carlstratton.co.uk

**Comment by hdrdavies** [comment]
Thanks for your quick response @carlstratton :smile: 

We can't do this Wednesday - but how about Thursday?

**Comment by carlstratton** [comment]
I'm stacked this week and can only do Wednesday – you guys can do Thursday
if you like?

Carl


*— *

t: 07824 632 199
e: cgstratton@gmail.com

senior UX designer at farfetch <http://www.farfetch.com>
co-founder | emblzn.com
designer | carlstratton.co.uk
